# Generated by Django 6.0.6 on 2026-06-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoesgrid',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
