# Generated by Django 6.0.6 on 2026-06-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_shoesgrid_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('hoodies', 'Hoodies'), ('tshirts', 'T-Shirts'), ('shirts', 'Shirts'), ('bottomwear', 'Bottom Wear'), ('accessories', 'Accessories'), ('shoes', 'Shoes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sizetemplate',
            name='category_type',
            field=models.CharField(choices=[('hoodies', 'Hoodies'), ('tshirts', 'T-Shirts'), ('shirts', 'Shirts'), ('bottomwear', 'Bottom Wear'), ('accessories', 'Accessories'), ('shoes', 'Shoes')], max_length=20, unique=True),
        ),
    ]
