# Generated by Django 6.0.6 on 2026-06-25 20:18
# Custom 3-step migration: add field → backfill SKUs → add unique constraint

from django.db import migrations, models


def backfill_size_stock_skus(apps, schema_editor):
    """Populate the sku field for all existing SizeStock rows."""
    SizeStock = apps.get_model('products', 'SizeStock')
    for ss in SizeStock.objects.select_related('variant').all():
        if not ss.sku:
            ss.sku = f"{ss.variant.sku}-{ss.size}"
            ss.save(update_fields=['sku'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_category_type_and_more'),
    ]

    operations = [
        # Step 1: Add the sku field WITHOUT unique=True so existing rows can be empty
        migrations.AddField(
            model_name='sizestock',
            name='sku',
            field=models.CharField(blank=True, max_length=120, default=''),
        ),
        # Step 2: Backfill existing rows with auto-generated SKUs
        migrations.RunPython(backfill_size_stock_skus, migrations.RunPython.noop),
        # Step 3: Now enforce uniqueness
        migrations.AlterField(
            model_name='sizestock',
            name='sku',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
