# Generated by Django 6.0.6 on 2026-08-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('attempted', 'Attempted'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('requires_action', 'Requires Action')], default='created', max_length=20),
        ),
    ]
